steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/koraflow-dev-123/frappe:latest', '-f', 'deploy/Dockerfile', '.']
    dir: '.'
images:
  - 'gcr.io/koraflow-dev-123/frappe:latest'
