#!/usr/bin/env python3
"""
Script to ask Ollama for guidance on creating a signup wizard form
"""

import sys
import os
import requests
import json
import yaml
from pathlib import Path

# Add parent directory to path to import ollama_client
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

# Import OllamaClient but we'll handle config loading ourselves
from llm_service.ollama_client import OllamaClient

def load_config_local():
    """Load config from local config.yml"""
    config_path = Path(__file__).parent.parent / "config.yml"
    if not config_path.exists():
        # Fallback to default config
        return {
            'ollama': {
                'host': os.getenv('OLLAMA_HOST', 'localhost'),
                'port': int(os.getenv('OLLAMA_PORT', 11434)),
                'model': os.getenv('OLLAMA_MODEL', 'llama3')
            }
        }
    with open(config_path, 'r') as f:
        config = yaml.safe_load(f)
    
    # Override Docker hostname with localhost when running locally
    if config.get('ollama', {}).get('host') == 'host.docker.internal':
        config['ollama']['host'] = 'localhost'
    
    return config

def ask_ollama_about_wizard():
    """Ask Ollama for guidance on creating a signup wizard"""
    
    # Load config locally
    config = load_config_local()
    client = OllamaClient(config=config)
    
    prompt = """I'm building a signup wizard form in Frappe/ERPNext (now KoraFlow) similar to the onboarding wizard. 
I need to create a multi-step form for user registration with custom fields.

Please provide guidance on:
1. How to structure a multi-step wizard form in Frappe (similar to the Insights Setup.vue pattern)
2. How to create a custom DocType for storing signup data
3. How to implement step navigation (Next/Back buttons)
4. How to validate and save data at each step
5. How to handle form state across steps
6. Best practices for custom fields in signup forms

Please provide:
- Vue.js component structure (similar to Setup.vue)
- DocType JSON structure for the signup data
- Python API methods for saving data
- Step-by-step implementation guide

Focus on practical, working code examples."""
    
    print("Asking Ollama for wizard creation guidance...")
    print("=" * 60)
    
    try:
        response = client.generate(
            prompt=prompt,
            temperature=0.7,
            max_tokens=2000
        )
        
        print(response)
        print("\n" + "=" * 60)
        
        # Save response to file
        output_file = os.path.join(os.path.dirname(__file__), '..', 'WIZARD_GUIDE.md')
        with open(output_file, 'w') as f:
            f.write("# Signup Wizard Creation Guide\n\n")
            f.write("Generated by Ollama\n\n")
            f.write(response)
        
        print(f"\nGuide saved to: {output_file}")
        
    except Exception as e:
        print(f"Error: {e}")
        return False
    
    return True

if __name__ == "__main__":
    if not ask_ollama_about_wizard():
        sys.exit(1)

